site_name: Slack Notification

nav:
  - How to integrate Gitlab with Slack: gitlab/gitlab.md
  - How to integrate Jira with Slack: jira/jira.md
  - How to integrate Jenkins with Slack: jenkins/jenkins.md
theme: readthedocs
