site_name: Slack Notification

nav:
  - How to integrate Gitlab with Slack: gitlab.md
  - How to integrate Jira with Slack: jira.md
  - How to integrate Jenkins with Slack: jenkins/jenkins.md
theme: readthedocs
